# NumPy
- NumPy is a powerful library for numerical computing in Python
- NumPy's primary data structure is the **array**. These arrays are similar to Python lists but more efficient for numerical computations. They can be one-dimensional, two-dimensional (**matrices**).
- NumPy arrays are more efficient than Python lists because they are homogeneous (all elements have the same data type) and stored in contiguous memory. This design allows for faster operations on large datasets.
- To install NumPy using conda
    - conda install numpy

## Importing NumPy

In [1]:
# To use NumPy, we need to import it into our notebook.
import numpy as np

In [2]:
# Check NumPy version
np.__version__

'1.24.3'

## Creating NumPy Arrays
- We can create NumPy arrays using various methods.

In [3]:
# Creating a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

[1 2 3 4 5]


In [4]:
# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# Creating NumPy arrays with functions
# NumPy provides several functions for creating arrays.

# Creating an array of zeros
zeros_array = np.zeros((3, 4))

# Creating an array of ones
ones_array = np.ones((2, 2))

# Creating an identity matrix
identity_matrix = np.eye(3)

# Display the arrays
print("Zeros Array:")
print(zeros_array)
print()
print("Ones Array:")
print(ones_array)
print()
print("Identity Matrix:")
print(identity_matrix)

Zeros Array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones Array:
[[1. 1.]
 [1. 1.]]

Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# Creating an array using arange
# The "arange" function creates a range of values with specified start, end, and step size.
arange_array = np.arange(1, 11, 2)

# Display the arange array
print("Arange Array:")
print(arange_array)

Arange Array:
[1 3 5 7 9]


In [7]:
# Creating an array using linspace
# The "linspace" function creates an array of evenly spaced values within a specified range.
linspace_array = np.linspace(1, 10, 6)

# Display the linspace array
print("Linspace Array:")
print(linspace_array)

Linspace Array:
[ 1.   2.8  4.6  6.4  8.2 10. ]


## Array Properties
- NumPy arrays have various properties that provide information about their dimensions, shape, and data type.

In [8]:
sample_array = np.array([[1, 2, 3], [4, 5, 6]])
print(sample_array)
print()

# The "shape" property provides information about the dimensions of the array.
array_shape = sample_array.shape
# Display the array shape
print("Array Shape:", array_shape)

# The "ndim" property returns the number of dimensions of the array.
num_dimensions = sample_array.ndim
# Display the number of dimensions
print("Number of Dimensions:", num_dimensions)

# The "dtype" property shows the data type of the elements in the array.
data_type = sample_array.dtype
# Display the data type
print("Data Type:", data_type)

# We can calculate the total number of elements in the array using the "size" property.
num_elements = sample_array.size
# Display the number of elements
print("Number of Elements:", num_elements)

[[1 2 3]
 [4 5 6]]

Array Shape: (2, 3)
Number of Dimensions: 2
Data Type: int32
Number of Elements: 6


## Array Operations
- NumPy provides a wide range of operations for performing mathematical and array-based computations on arrays.

In [9]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Display the arrays
print("Array 1:", array1)
print("Array 2:", array2)

print()

# Addition
addition_result = array1 + array2

# Subtraction
subtraction_result = array1 - array2

# Multiplication
multiplication_result = array1 * array2

# Division
division_result = array1 / array2

# Scalar Addition
scalar_addition = array1 + 10

# Display the results
print("Addition Result:", addition_result)
print("Subtraction Result:", subtraction_result)
print("Multiplication Result:", multiplication_result)
print("Division Result:", division_result)
print("Scalar Addition Result:", scalar_addition)

Array 1: [1 2 3]
Array 2: [4 5 6]

Addition Result: [5 7 9]
Subtraction Result: [-3 -3 -3]
Multiplication Result: [ 4 10 18]
Division Result: [0.25 0.4  0.5 ]
Scalar Addition Result: [11 12 13]


In [10]:
# NumPy arrays can also perform operations with arrays of different shapes, thanks to broadcasting.

# Array with Different Shape
array1 = np.array([1, 2, 3])
array2 = np.ones((3,1))

# Display the arrays
print("Array 1:", array1)
print("Array 2:")
print(array2)

print()

broadcast_result = array1 + array2

# Display the results
print("Broadcast Result:")
print(broadcast_result)

Array 1: [1 2 3]
Array 2:
[[1.]
 [1.]
 [1.]]

Broadcast Result:
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [11]:
# NumPy provides a wide range of functions for performing operations on arrays.
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Display the arrays
print("Array 1:", array1)
print("Array 2:", array2)

print()

# The "numpy.sum" function calculates the sum of elements in an array.
sum_array1 = np.sum(array1)

# The "np.add" function perform element-wise addition of two arrays.
elementwise_add = np.add(array1, array2)

# The "subtract" function performs element-wise subtraction of two arrays.
elementwise_subtract = np.subtract(array1, array2)

# The "dot" function computes the dot product of two arrays.
dot_product = np.dot(array1, array2)

# The "multiply" function performs element-wise multiplication of two arrays.
elementwise_multiply = np.multiply(array1, array2)

# The "prod" function calculates the product of all elements in an array.
product_result = np.prod(array1)

# The "divide" function performs element-wise division of two arrays.
elementwise_divide = np.divide(array1, array2)

# The "floor_divide" function performs element-wise floor division of two arrays.
floor_divide_result = np.floor_divide(array1, array2)

# Display the results
print("Sum of Array 1:", sum_array1)
print("Element-wise Add Result:", elementwise_add)
print("Element-wise Subtraction Result:", elementwise_subtract)
print("Dot Product Result:", dot_product)
print("Element-wise Multiplication Result:", elementwise_multiply)
print("Product of Array Elements:", product_result)
print("Element-wise Division Result:", elementwise_divide)
print("Floor Division Result:", floor_divide_result)

Array 1: [1 2 3]
Array 2: [4 5 6]

Sum of Array 1: 6
Element-wise Add Result: [5 7 9]
Element-wise Subtraction Result: [-3 -3 -3]
Dot Product Result: 32
Element-wise Multiplication Result: [ 4 10 18]
Product of Array Elements: 6
Element-wise Division Result: [0.25 0.4  0.5 ]
Floor Division Result: [0 0 0]


In [12]:
# The cumulative sum (also known as a running total) is a sequence of partial sums of an array. 
# Computing the cumulative sum along specific axes is valuable when working with multi-dimensional data.

array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Display the original 2D array
print("Original 2D Array:")
print(array_2d)

print()

# We can compute the cumulative sum along axis 0 (by each row) using the "cumsum" function with "axis=0".
cumulative_sum_axis0 = np.cumsum(array_2d, axis=0)

# We can compute the cumulative sum along axis 1 (by each column) using the "cumsum" function with "axis=1".
cumulative_sum_axis1 = np.cumsum(array_2d, axis=1)

# Display the results
print("Cumulative Sum along Axis 0:")
print(cumulative_sum_axis0)
print("Cumulative Sum along Axis 1:")
print(cumulative_sum_axis1)

Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Cumulative Sum along Axis 0:
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
Cumulative Sum along Axis 1:
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


## Array Mathematical Functions
- NumPy provides a wide range of mathematical functions that can be applied to arrays to perform element-wise computations.

In [13]:
array = np.array([1, 2, 3, 4, 5])

# Display the array
print("Array:")
print(array)

print()

# The "np.mean" function calculates the mean (average) of elements in an array.
mean_result = np.mean(array)

# The "sqrt" function computes the square root of each element in the array.
sqrt_result = np.sqrt(array)

# The "exp" function computes the exponential (e^x) of each element in the array.
exp_result = np.exp(array)

# Display the results
print("Mean of the Array:", mean_result)
print("Square Root Result:", sqrt_result)
print("Exponential Result:", exp_result)
print()

Array:
[1 2 3 4 5]

Mean of the Array: 3.0
Square Root Result: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential Result: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]



In [14]:
# The "np.polyval" function evaluates a polynomial at a given point.

# Define a polynomial coefficients array
coefficients = [1, 2, 3]

# Evaluate the polynomial at x = 2
x = 2
polyval_result = np.polyval(coefficients, x)

# Display the polynomial evaluation result
print("Evaluation of Polynomial at x =", x, "is", polyval_result)

Evaluation of Polynomial at x = 2 is 11


In [15]:
# The "np.polyder" function returns the coefficients of the derivative of a polynomial.

# Define a polynomial coefficients array
coefficients = [1, 2, 3]

# Find the derivative of the polynomial
derivative = np.polyder(coefficients)

# Display the derivative coefficients
print("Derivative Coefficients:", derivative)

Derivative Coefficients: [2 2]


In [16]:
# The "np.polyint" function returns the coefficients of the indefinite integral of a polynomial.

# Define a polynomial coefficients array
coefficients = [1, 2, 3]

# Find the integral of the polynomial
integral = np.polyint(coefficients)

# Display the integral coefficients
print("Integral Coefficients:", integral)

Integral Coefficients: [0.33333333 1.         3.         0.        ]


In [17]:
# NumPy defines "np.nan" to represent a missing or undefined value in numerical computations.
nan_value = np.nan

# Check if a value is NaN
is_nan = np.isnan(nan_value)

# Display NaN and check result
print("NaN:", nan_value)
print("Is NaN:", is_nan)

NaN: nan
Is NaN: True


In [18]:
# NumPy defines "np.inf" to represent positive infinity and "-np.inf" for negative infinity.

positive_infinity = np.inf
negative_infinity = -np.inf

# Display positive and negative infinity
print("Positive Infinity:", positive_infinity)
print("Negative Infinity:", negative_infinity)

Positive Infinity: inf
Negative Infinity: -inf


## Generating Random Numbers
- NumPy provides functions for generating random numbers, which can be useful for various applications such as simulations and random sampling.

In [19]:
# The "np.random.random" function generates random numbers from a uniform distribution in the range [0.0, 1.0).

# Generating 5 random numbers
random_numbers = np.random.random(5)

# We can generate random numbers with a specific shape using the "size" parameter.
# Generating a 3x2 array of random numbers
random_matrix = np.random.random((3, 2))

# Display the generated random numbers
print("Random Numbers from a Uniform Distribution:")
print(random_numbers)

print() 

print("Random Matrix (3x2) from a Uniform Distribution:")
print(random_matrix)

Random Numbers from a Uniform Distribution:
[0.70917202 0.6373829  0.10334913 0.81225806 0.84007579]

Random Matrix (3x2) from a Uniform Distribution:
[[0.68471279 0.30274966]
 [0.10620358 0.12907785]
 [0.20776103 0.71697081]]


In [20]:
# The "np.random.uniform" function generates random numbers from a uniform distribution within a specified range.

# Generating 5 random numbers between 0 and 1
uniform_random_numbers = np.random.uniform(0, 1, 5)

# Display the generated random numbers
print("Random Numbers from Uniform Distribution:")
print(uniform_random_numbers)

Random Numbers from Uniform Distribution:
[0.51138338 0.36093409 0.68052205 0.83195245 0.57327963]


In [21]:
# The "np.random.standard_normal" function generates random numbers from a standard normal (Gaussian) distribution with mean 0 and standard deviation 1.

# Generating 5 random numbers from the standard normal distribution
standard_normal_numbers = np.random.standard_normal(5)

# Display the generated standard normal random numbers
print("Random Numbers from Standard Normal Distribution:")
print(standard_normal_numbers)

Random Numbers from Standard Normal Distribution:
[ 0.33515263  1.43261558 -0.0656244  -2.01613847  0.56147703]


## Working with Unique Elements, Union, and Intersection
- NumPy provides functions for working with unique elements, calculating the union and intersection of arrays.

In [22]:
array1 = np.array([1, 2, 3, 4, 5, 5])
array2 = np.array([4, 5, 6, 6, 7, 8])

# Display the arrays
print("Array 1:", array1)
print("Array 2:", array2)

print()

# The "np.unique" function returns the unique elements of an array.
unique_array1 = np.unique(array1)
unique_array2 = np.unique(array2)

# The "np.union1d" function calculates the union of two arrays, preserving unique values from both arrays.
union_result = np.union1d(array1, array2)

# The "np.intersect1d" function calculates the intersection of two arrays, preserving unique values common to both arrays.
intersection_result = np.intersect1d(array1, array2)

# Display unique elements
print("Unique elements in Array 1:", unique_array1)
print("Unique elements in Array 2:", unique_array2)
print("Union of Array 1 and Array 2:", union_result)
print("Intersection of Array 1 and Array 2:", intersection_result)

Array 1: [1 2 3 4 5 5]
Array 2: [4 5 6 6 7 8]

Unique elements in Array 1: [1 2 3 4 5]
Unique elements in Array 2: [4 5 6 7 8]
Union of Array 1 and Array 2: [1 2 3 4 5 6 7 8]
Intersection of Array 1 and Array 2: [4 5]


## Slicing and Reshaping
- NumPy provides powerful tools for slicing arrays and reshaping them to meet various data manipulation needs.

In [23]:
# Let's create a NumPy array to demonstrate slicing and reshaping.
original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])

# Display the original array
print("Original Array:")
print(original_array)

print()

# Slicing a single element
element = original_array[1, 2]

# Slicing a row
row = original_array[0, :]

# Slicing a column
column = original_array[:, 2]

# NumPy allows us to reshape arrays into different dimensions.
# Reshaping into a 4x3 array
reshaped_array = original_array.reshape(4, 3)

# Display the results
print("Sliced Element:", element)
print("Sliced Row:", row)
print("Sliced Column:", column)
print("Reshaped Array (4x3):")
print(reshaped_array)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Sliced Element: 7
Sliced Row: [1 2 3 4]
Sliced Column: [ 3  7 11]
Reshaped Array (4x3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
