Type        
Integer  5
Float 3,14
String 'Helo'
Boolean True/False

In [1]:
x = 10
y = 3.5
name = 'Murilo'
is_happy = True

In [2]:
print(type(x))
print(type(y))
print(type(name))
print(type(is_happy))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [3]:
last = 'Farias'
full = name + " " + last
print(full)

Murilo Farias


In [4]:
fruits = ['apple', 'banana', 'cherry']
print(fruits)

['apple', 'banana', 'cherry']


In [5]:
fruits.append('orange')
print(len(fruits))
print(fruits)

4
['apple', 'banana', 'cherry', 'orange']


In [6]:
person = {'name': 'Nisa', 'age': 30}

In [7]:
print(person['name'])

Nisa


In [8]:
person['city'] = 'Vancouver'

In [9]:
print(person)

{'name': 'Nisa', 'age': 30, 'city': 'Vancouver'}


In [10]:
x = 10
if x > 5:
    print('Big Number')
else:
    print('Smal number')

Big Number


In [11]:
x = 4
if x > 5:
    print('Big Number')
else:
    print('Smal number')

Smal number


In [12]:
for i in range(5):
    print(i)

0
1
2
3
4


In [13]:
count = 0
while count < 5 :
    print(count)
    count +=1

0
1
2
3
4


In [14]:
def greet(name):
    return 'hello ' + name

print(greet('Murilo'))

hello Murilo


In [15]:
import math

In [16]:
print(math.sqrt(16))

4.0


In [17]:
#We could say is a table

import pandas as pd
data = pd.DataFrame({
    'Name': ['Nisa', 'Murilo'], 'Age': [30,25]
})

print(data)

     Name  Age
0    Nisa   30
1  Murilo   25


In [18]:
import numpy as np
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [19]:
print(arr +5)

[6 7 8]


In [20]:
print(arr)

[1 2 3]


In [21]:
import pandas as pd
data = pd.DataFrame({
'Age':[25,30,22,35],
'Salary':[5000,60000,45000,7000],
'Purchased': [0,1,0,1]
})

In [22]:
print(data)

   Age  Salary  Purchased
0   25    5000          0
1   30   60000          1
2   22   45000          0
3   35    7000          1


In [23]:
df = pd.read_csv('college.csv')

In [24]:
print(df.head())

                     Unnamed: 0 Private  Apps  Accept  Enroll  Top10perc  \
0  Abilene Christian University     Yes  1660    1232     721         23   
1            Adelphi University     Yes  2186    1924     512         16   
2                Adrian College     Yes  1428    1097     336         22   
3           Agnes Scott College     Yes   417     349     137         60   
4     Alaska Pacific University     Yes   193     146      55         16   

   Top25perc  F.Undergrad  P.Undergrad  Outstate  Room.Board  Books  Personal  \
0         52         2885          537      7440        3300    450      2200   
1         29         2683         1227     12280        6450    750      1500   
2         50         1036           99     11250        3750    400      1165   
3         89          510           63     12960        5450    450       875   
4         44          249          869      7560        4120    800      1500   

   PhD  Terminal  S.F.Ratio  perc.alumni  Expend  Grad.R

In [25]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 777 entries, 0 to 776
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Unnamed: 0   777 non-null    object 
 1   Private      777 non-null    object 
 2   Apps         777 non-null    int64  
 3   Accept       777 non-null    int64  
 4   Enroll       777 non-null    int64  
 5   Top10perc    777 non-null    int64  
 6   Top25perc    777 non-null    int64  
 7   F.Undergrad  777 non-null    int64  
 8   P.Undergrad  777 non-null    int64  
 9   Outstate     777 non-null    int64  
 10  Room.Board   777 non-null    int64  
 11  Books        777 non-null    int64  
 12  Personal     777 non-null    int64  
 13  PhD          777 non-null    int64  
 14  Terminal     777 non-null    int64  
 15  S.F.Ratio    777 non-null    float64
 16  perc.alumni  777 non-null    int64  
 17  Expend       777 non-null    int64  
 18  Grad.Rate    777 non-null    int64  
dtypes: float

In [26]:
print(df.describe())

               Apps        Accept       Enroll   Top10perc   Top25perc  \
count    777.000000    777.000000   777.000000  777.000000  777.000000   
mean    3001.638353   2018.804376   779.972973   27.558559   55.796654   
std     3870.201484   2451.113971   929.176190   17.640364   19.804778   
min       81.000000     72.000000    35.000000    1.000000    9.000000   
25%      776.000000    604.000000   242.000000   15.000000   41.000000   
50%     1558.000000   1110.000000   434.000000   23.000000   54.000000   
75%     3624.000000   2424.000000   902.000000   35.000000   69.000000   
max    48094.000000  26330.000000  6392.000000   96.000000  100.000000   

        F.Undergrad   P.Undergrad      Outstate   Room.Board        Books  \
count    777.000000    777.000000    777.000000   777.000000   777.000000   
mean    3699.907336    855.298584  10440.669241  4357.526384   549.380952   
std     4850.420531   1522.431887   4023.016484  1096.696416   165.105360   
min      139.000000      

In [27]:
print(df['Apps'].mean())

3001.6383526383524


In [28]:
df.isnull().sum()

Unnamed: 0     0
Private        0
Apps           0
Accept         0
Enroll         0
Top10perc      0
Top25perc      0
F.Undergrad    0
P.Undergrad    0
Outstate       0
Room.Board     0
Books          0
Personal       0
PhD            0
Terminal       0
S.F.Ratio      0
perc.alumni    0
Expend         0
Grad.Rate      0
dtype: int64

**************** Multiple Linear Regression **************

y = b0 + b1x1 + b2x2 + error

In [29]:
import statsmodels.api as sm
import pandas as pd
df_dois = pd.DataFrame({
'Age':[25,30,22,35],
'Salary':[50000,60000,45000,70000],
'Experience': [0,1,0,1]
})

In [30]:
X = df_dois[['Age', 'Experience']]
y = df_dois['Salary']
X = sm.add_constant(X)
#OLS is the fcuntion for Multiple linear Regression
model = sm.OLS(y, X).fit()

In [31]:
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                 Salary   R-squared:                       0.999
Model:                            OLS   Adj. R-squared:                  0.997
Method:                 Least Squares   F-statistic:                     501.0
Date:                Wed, 24 Sep 2025   Prob (F-statistic):             0.0316
Time:                        15:11:25   Log-Likelihood:                -28.533
No. Observations:                   4   AIC:                             63.07
Df Residuals:                       1   BIC:                             61.22
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2573.5294   3482.377      0.739      0.5

c:\Users\MuriloFarias\anaconda3\Lib\site-packages\statsmodels\stats\stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 4 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "


In [32]:
X_new = pd.DataFrame({
'Age':[28,40],
'Experience': [3,15]
})

In [33]:
X_new = sm.add_constant(X_new)
y_pred = model.predict(X_new)
print(y_pred)

0    56985.294118
1    83455.882353
dtype: float64


**************** LOGISTIC REGRESSION **************

logit(p) = ln(p / 1-p) = b0 + b1x1 + b2x2

In [34]:
import pandas as pd
import statsmodels.api as sm

In [35]:

data = pd.DataFrame({
'Age':[22,25,27,30,32,35,40,45,50,55],
'Salary':[40000,48000,50000,52000,60000,65000,70000,72000,75000,80000],
'Purchased': [0,0,0,1,1,0,1,1,0,1]
})

In [36]:
data["Sallary"] = data["Salary"]/1000  #scaling the salary to make the model better

In [37]:
X = sm.add_constant(data[['Age', 'Sallary']])
y = data['Purchased']

In [38]:
logit_model = sm.Logit(y, X).fit()

Optimization terminated successfully.
         Current function value: 0.583679
         Iterations 5


In [39]:
print(logit_model.summary())

                           Logit Regression Results                           
Dep. Variable:              Purchased   No. Observations:                   10
Model:                          Logit   Df Residuals:                        7
Method:                           MLE   Df Model:                            2
Date:                Wed, 24 Sep 2025   Pseudo R-squ.:                  0.1579
Time:                        15:11:26   Log-Likelihood:                -5.8368
converged:                       True   LL-Null:                       -6.9315
Covariance Type:            nonrobust   LLR p-value:                    0.3346
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -6.0497      5.562     -1.088      0.277     -16.950       4.851
Age           -0.0793      0.271     -0.293      0.769      -0.610       0.451
Sallary        0.1450      0.232      0.626      0.5

In [40]:
X_new = pd.DataFrame({
'Age':[30,45], "salary": [55000,80000]
})

In [41]:
X_new = sm.add_constant(X_new)

In [42]:
y_prob = logit_model.predict(X_new)

In [43]:
y_pred = (y_prob > 0.5).astype(int)

In [44]:
print(y_prob)
print(y_pred)

0    1.0
1    1.0
dtype: float64
0    1
1    1
dtype: int32


 ERROR SMALL DATA

In [45]:
import pandas as pd
import statsmodels.api as sm

new_data = pd.DataFrame({
'Age':[22,25,27,30,32,35,40,45,50,55],
'Salary':[40000,48000,50000,52000,60000,65000,70000,72000,75000,80000],
'Purchased': [0,0,0,1,1,0,1,1,0,1]
})

In [46]:
X = new_data[['Age', 'Salary']]
y = new_data['Purchased']


In [47]:
X = sm.add_constant(X)

In [48]:
logit_model = sm.Logit(y, X).fit()

Optimization terminated successfully.
         Current function value: 0.583679
         Iterations 5


In [49]:
print(logit_model.summary())

                           Logit Regression Results                           
Dep. Variable:              Purchased   No. Observations:                   10
Model:                          Logit   Df Residuals:                        7
Method:                           MLE   Df Model:                            2
Date:                Wed, 24 Sep 2025   Pseudo R-squ.:                  0.1579
Time:                        15:11:26   Log-Likelihood:                -5.8368
converged:                       True   LL-Null:                       -6.9315
Covariance Type:            nonrobust   LLR p-value:                    0.3346
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -6.0497      5.562     -1.088      0.277     -16.950       4.851
Age           -0.0793      0.271     -0.293      0.769      -0.610       0.451
Salary         0.0001      0.000      0.626      0.5

In [50]:
X_new = pd.DataFrame({"Age":[30,45], "Salary": [55000,80000]})

In [51]:
X_new = sm.add_constant(X_new)

In [52]:
y_prob = logit_model.predict(X_new)

In [53]:
y_pred = (y_prob > 0.5).astype(int)

In [54]:
print(y_prob)

0    0.388369
1    0.878792
dtype: float64


In [55]:

print(y_pred)

0    0
1    1
dtype: int32
